# Generated by Django 5.2.16 on 2026-07-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttapp', '0006_trendingtracks_mood'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('song', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200)),
                ('popularity', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, default='', max_length=200)),
                ('release_year', models.CharField(blank=True, default='', max_length=200)),
                ('genres', models.CharField(blank=True, default='', max_length=200)),
                ('artist_uri', models.CharField(blank=True, default='', max_length=200)),
                ('source_label', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
