# Generated by Django 5.2.16 on 2026-07-10 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tttapp', '0007_playlisttrack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendingTracks',
        ),
    ]
