# Generated by Django 5.2.16 on 2026-07-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tttapp', '0008_delete_trendingtracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlisttrack',
            name='artist_uri',
        ),
        migrations.RemoveField(
            model_name='playlisttrack',
            name='genres',
        ),
    ]
