# Generated by Django 5.2.16 on 2026-07-14 10:24

from django.db import migrations, models


def backfill_position(apps, schema_editor):
    """Preserve today's -id (newest first) ordering by seeding
    position = id, so migrating doesn't visibly reorder anyone's queue."""
    PlaylistTrack = apps.get_model('tttapp', 'PlaylistTrack')
    for track in PlaylistTrack.objects.all():
        track.position = track.id
        track.save(update_fields=['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('tttapp', '0009_remove_playlisttrack_artist_uri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spotify_playlist_id', models.CharField(blank=True, default='', max_length=200)),
                ('csv_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_position, migrations.RunPython.noop),
    ]
